name: ppieces Tests

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permissions
      contents: write

    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements/test.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Print Python path
      run: python -c "import sys; print(sys.path)"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/test.txt
        pip install .

    - name: Run tests
      run: |
        make cov

    - name: Generate coverage badge
      uses: tj-actions/coverage-badge-py@v2
      with:
        output: 'coverage.svg'
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    - name: Push coverage badge
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Automatic GH Actions: coverage badge"
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
